
extern zend_class_entry *leevel_http_irequest_ce;

ZEPHIR_INIT_CLASS(Leevel_Http_IRequest);

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_reset, 0, 0, 0)
	ZEND_ARG_ARRAY_INFO(0, query, 1)
	ZEND_ARG_ARRAY_INFO(0, request, 1)
	ZEND_ARG_ARRAY_INFO(0, params, 1)
	ZEND_ARG_ARRAY_INFO(0, cookies, 1)
	ZEND_ARG_ARRAY_INFO(0, files, 1)
	ZEND_ARG_ARRAY_INFO(0, server, 1)
	ZEND_ARG_INFO(0, content)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_normalizerequestfromcontent, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, request, Leevel\\Http\\Request, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_get, 0, 0, 1)
	ZEND_ARG_INFO(0, key)
	ZEND_ARG_INFO(0, defaults)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_exists, 0, 0, 1)
	ZEND_ARG_INFO(0, key)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_input, 0, 0, 0)
	ZEND_ARG_INFO(0, key)
	ZEND_ARG_INFO(0, defaults)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_query, 0, 0, 0)
	ZEND_ARG_INFO(0, key)
	ZEND_ARG_INFO(0, defaults)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_hascookie, 0, 0, 1)
	ZEND_ARG_INFO(0, key)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_cookie, 0, 0, 0)
	ZEND_ARG_INFO(0, key)
	ZEND_ARG_INFO(0, defaults)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_file, 0, 0, 0)
	ZEND_ARG_INFO(0, key)
	ZEND_ARG_INFO(0, defaults)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_hasfile, 0, 0, 1)
	ZEND_ARG_INFO(0, key)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_isvalidfile, 0, 0, 1)
	ZEND_ARG_INFO(0, file)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_header, 0, 0, 0)
	ZEND_ARG_INFO(0, key)
	ZEND_ARG_INFO(0, defaults)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_server, 0, 0, 0)
	ZEND_ARG_INFO(0, key)
	ZEND_ARG_INFO(0, defaults)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_getitem, 0, 0, 3)
	ZEND_ARG_INFO(0, source)
	ZEND_ARG_INFO(0, key)
	ZEND_ARG_INFO(0, defaults)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_merge, 0, 0, 1)
	ZEND_ARG_ARRAY_INFO(0, input, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_replace, 0, 0, 1)
	ZEND_ARG_ARRAY_INFO(0, input, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_setmethod, 0, 0, 1)
	ZEND_ARG_INFO(0, method)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_ismethod, 0, 0, 1)
	ZEND_ARG_INFO(0, method)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_setapp, 0, 0, 1)
	ZEND_ARG_INFO(0, app)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_setcontroller, 0, 0, 1)
	ZEND_ARG_INFO(0, controller)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_setaction, 0, 0, 1)
	ZEND_ARG_INFO(0, action)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_setlanguage, 0, 0, 1)
	ZEND_ARG_INFO(0, language)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_leevel_http_irequest_setpathinfo, 0, 0, 1)
	ZEND_ARG_INFO(0, pathInfo)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(leevel_http_irequest_method_entry) {
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, reset, arginfo_leevel_http_irequest_reset)
	ZEND_FENTRY(createFromGlobals, NULL, NULL, ZEND_ACC_STATIC|ZEND_ACC_ABSTRACT|ZEND_ACC_PUBLIC)
	ZEND_FENTRY(normalizeRequestFromContent, NULL, arginfo_leevel_http_irequest_normalizerequestfromcontent, ZEND_ACC_STATIC|ZEND_ACC_ABSTRACT|ZEND_ACC_PUBLIC)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, get, arginfo_leevel_http_irequest_get)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, exists, arginfo_leevel_http_irequest_exists)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, has, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, only, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, except, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, all, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, input, arginfo_leevel_http_irequest_input)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, query, arginfo_leevel_http_irequest_query)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, hasCookie, arginfo_leevel_http_irequest_hascookie)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, cookie, arginfo_leevel_http_irequest_cookie)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, allFiles, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, file, arginfo_leevel_http_irequest_file)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, hasFile, arginfo_leevel_http_irequest_hasfile)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isValidFile, arginfo_leevel_http_irequest_isvalidfile)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, header, arginfo_leevel_http_irequest_header)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, server, arginfo_leevel_http_irequest_server)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getItem, arginfo_leevel_http_irequest_getitem)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, merge, arginfo_leevel_http_irequest_merge)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, replace, arginfo_leevel_http_irequest_replace)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isCli, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isRealCli, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isCgi, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isAjax, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isRealAjax, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isXmlHttpRequest, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isPjax, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isRealPjax, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isJson, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isRealJson, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isAcceptJson, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isRealAcceptJson, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isAcceptAny, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isMobile, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isHead, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isGet, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isPost, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isPut, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isPatch, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isPurge, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isOptions, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isTrace, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isConnect, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getClientIp, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getMethod, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, setMethod, arginfo_leevel_http_irequest_setmethod)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getRealMethod, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isMethod, arginfo_leevel_http_irequest_ismethod)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, app, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, controller, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, action, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getNode, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, setApp, arginfo_leevel_http_irequest_setapp)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, setController, arginfo_leevel_http_irequest_setcontroller)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, setAction, arginfo_leevel_http_irequest_setaction)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, language, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getLanguage, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, setLanguage, arginfo_leevel_http_irequest_setlanguage)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getContent, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getRoot, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getEnter, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getScriptName, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, isSecure, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getHttpHost, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getHost, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getSchemeAndHttpHost, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getUri, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getPort, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getScheme, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getQueryString, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, setPathInfo, arginfo_leevel_http_irequest_setpathinfo)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getPathInfo, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getBasePath, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getBaseUrl, NULL)
	PHP_ABSTRACT_ME(Leevel_Http_IRequest, getRequestUri, NULL)
	PHP_FE_END
};
